column_name:
- ID
- Category
- Text
filename_extension: '.tsv'
train_ratio: 0.8
valid_test_ratio: 0.5
min_category_num: 8
max_len_chunk: 512
data_augment_num: 5
random_state: 777
tokenizer_type: 'None'