model_type: None
text_dataset: None
base_dir: None
gpu_id: None
load_trained_model: None
load_model_name: None
filename_extension: '.tsv'

tokenizer:
  padding: 'max_length'

dataloader:
  delimiter: '\t'
  column_names:
    - ID
    - Category
    - Text

trainer_args:
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 32
  num_train_epochs: 0.2
  evaluation_strategy: 'steps'
  steps: 200
  learning_rate: 1e-3
  optim: 'adamw_torch'
  warmup_ratio: 0
  warmup_steps: 0
  lr_scheduler_type: 'cosine'
  output_dir: None
  logging_dir: None
  weight_decay: 0.1
  early_stopping_patience: 10

KoBERT:
  max_length: 32
